const CIRCLE_ARGUMENTS_LENGTH = 1;
const RECTANGLE_ARGUMENTS_LENGTH = 2;
const SQUARE_ARGUMENTS_LENGTH = 1;

export {
  CIRCLE_ARGUMENTS_LENGTH,
  RECTANGLE_ARGUMENTS_LENGTH,
  SQUARE_ARGUMENTS_LENGTH,
};
