const DRAW_CIRCLE_COMMAND_NAME = 'draw_circle';
const DRAW_RECTANGLE_COMMAND_NAME = 'draw_rectangle';
const DRAW_SQUARE_COMMAND_NAME = 'draw_square';

export {
  DRAW_CIRCLE_COMMAND_NAME,
  DRAW_RECTANGLE_COMMAND_NAME,
  DRAW_SQUARE_COMMAND_NAME,
};
