const PRINT_SCREEN_WIDTH = 200;
const PRINT_SCREEN_HEIGHT = 200;
const PRINT_SCREEN_HALF_WIDTH = 100;
const PRINT_SCREEN_HALF_HEIGHT = 100;

const BUFFER_ENCODING = 'base64';

export {
  PRINT_SCREEN_WIDTH,
  PRINT_SCREEN_HEIGHT,
  PRINT_SCREEN_HALF_WIDTH,
  PRINT_SCREEN_HALF_HEIGHT,
  BUFFER_ENCODING,
};
