export const MOUSE_UP = 'mouse_up';
export const MOUSE_DOWN = 'mouse_down';
export const MOUSE_LEFT = 'mouse_left';
export const MOUSE_RIGHT = 'mouse_right';
export const MOUSE_POSITION = 'mouse_position'; // click "p"
export const DRAW_CIRCLE = 'draw_circle'; // - click "c"
export const DRAW_SQUARE = 'draw_square'; // - click "s"
export const DRAW_RECTANGLE = 'draw_rectangle'; // - click "r"
export const PRNT_SCRN = 'prnt_scrn'; // - click "ctrl - p"